import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import Graph from "graphology";
import Sigma from "sigma";
import FA2Layout from "graphology-layout-forceatlas2/worker";
import louvain from "graphology-communities-louvain";
import pagerank from "graphology-metrics/centrality/pagerank";
import betweennessCentrality from "graphology-metrics/centrality/betweenness";
import { weightedDegree } from "graphology-metrics/node/weighted-degree";

type NodeRow = { id:string; label:string; frequency:number; sentenceFrequency:number; documentFrequency:number; pos:string };
type EdgeRow = { source:string; target:string; weight:number; sentenceIds:string; documentIds:string };
type Dataset = { nodes:NodeRow[]; edges:EdgeRow[]; name:string };
type Ranking = { id:string; value:number }[];
type Analysis = { title:string; description:string; nodes:Set<string>|null; path?:string[]; ranking?:Ranking };
type Tab = "explorar"|"caminos"|"comunidades"|"centralidad"|"comprender";

const palette=["#6f183f","#d94e80","#87983b","#5a8295","#d58a3a","#745aa8","#2b8d78","#b05242","#8e6b2f","#4d6db3","#b44776","#557d4a"];
const demo:Dataset={name:"Demostración — datos ficticios",nodes:Array.from({length:32},(_,i)=>({id:`Concepto ${i+1}`,label:`Concepto ${i+1}`,frequency:50-i,sentenceFrequency:35-i,documentFrequency:4,pos:i%5===0?"ADJ":"NOUN"})),edges:Array.from({length:75},(_,i)=>({source:`Concepto ${(i*7)%32+1}`,target:`Concepto ${(i*13+5)%32+1}`,weight:i%12+1,sentenceIds:"",documentIds:""})).filter(e=>e.source!==e.target)};

function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],field="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===','){row.push(field);field=""}else if(c==='\n'){row.push(field.replace(/\r$/, ""));rows.push(row);row=[];field=""}else field+=c}if(field||row.length){row.push(field);rows.push(row)}const headers=rows.shift()?.map(h=>h.trim().replace(/^\uFEFF/,""))??[];return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??""])))}
function colorFor(pos:string){const p=pos.toUpperCase();return p.includes("PROPN")?"#87983b":p.includes("ADJ")?"#d94e80":p.includes("VERB")?"#5a8295":"#6f183f"}
function shortestPath(graph:Graph,source:string,target:string){if(!graph.hasNode(source)||!graph.hasNode(target))return null;const queue=[source],previous=new Map<string,string|null>([[source,null]]);for(const node of queue){if(node===target)break;graph.forEachNeighbor(node,n=>{if(!previous.has(n)){previous.set(n,node);queue.push(n)}})}if(!previous.has(target))return null;const path:string[]=[];for(let n:string|null=target;n;n=previous.get(n)??null)path.push(n);return path.reverse()}

export default function App(){
 const containerRef=useRef<HTMLDivElement>(null),rendererRef=useRef<Sigma|null>(null),graphRef=useRef<Graph|null>(null);
 const [dataset,setDataset]=useState<Dataset>(demo),[query,setQuery]=useState(""),[minWeight,setMinWeight]=useState(1),[maxNodes,setMaxNodes]=useState(2000),[selected,setSelected]=useState<string|null>(null),[status,setStatus]=useState("Carga los dos CSV para comenzar"),[layoutRunning,setLayoutRunning]=useState(false);
 const [tab,setTab]=useState<Tab>("explorar"),[pathFrom,setPathFrom]=useState(""),[pathTo,setPathTo]=useState(""),[analysis,setAnalysis]=useState<Analysis>({title:"Grafo completo",description:"Vista general del vocabulario.",nodes:null}),[communities,setCommunities]=useState<Record<string,number>>({}),[busy,setBusy]=useState("");
 const ranked=useMemo(()=>[...dataset.nodes].sort((a,b)=>b.frequency-a.frequency),[dataset.nodes]);
 const visible=useMemo(()=>{const nodes=ranked.slice(0,Math.min(maxNodes,ranked.length)),ids=new Set(nodes.map(n=>n.id));return{nodes,edges:dataset.edges.filter(e=>e.weight>=minWeight&&ids.has(e.source)&&ids.has(e.target))}},[ranked,dataset.edges,maxNodes,minWeight]);
 const selectedNode=dataset.nodes.find(n=>n.id===selected),selectedEdges=selected?dataset.edges.filter(e=>e.source===selected||e.target===selected).sort((a,b)=>b.weight-a.weight).slice(0,10):[];
 const pathEdges=useMemo(()=>new Set((analysis.path??[]).slice(1).map((n,i)=>[analysis.path![i],n].sort().join("\u0000"))),[analysis.path]);
 const summary=useMemo(()=>{const n=visible.nodes.length,e=visible.edges.length,weights=visible.edges.reduce((s,x)=>s+x.weight,0);return{density:n>1?(2*e)/(n*(n-1)):0,averageDegree:n?2*e/n:0,averageWeight:e?weights/e:0}},[visible]);

 useEffect(()=>{if(!containerRef.current)return;rendererRef.current?.kill();const graph=new Graph({type:"undirected",multi:false,allowSelfLoops:false}),count=visible.nodes.length;
  visible.nodes.forEach((n,i)=>{const radius=Math.sqrt(i+1),angle=i*2.399963;graph.addNode(n.id,{label:n.label,x:Math.cos(angle)*radius,y:Math.sin(angle)*radius,size:3+Math.sqrt(Math.max(1,n.frequency))*.55,color:colorFor(n.pos),frequency:n.frequency,pos:n.pos})});
  visible.edges.forEach((e,i)=>{if(!graph.hasNode(e.source)||!graph.hasNode(e.target)||e.source===e.target)return;try{graph.addEdgeWithKey(`e${i}`,e.source,e.target,{size:.3+Math.sqrt(e.weight)*.25,color:"#baaeb4",weight:e.weight})}catch{/* pares duplicados */}});
  const renderer=new Sigma(graph,containerRef.current,{renderEdgeLabels:false,labelDensity:count>900?.05:count>400?.18:.6,labelGridCellSize:count>900?180:100,labelRenderedSizeThreshold:count>700?8:6,minCameraRatio:.03,maxCameraRatio:12,zIndex:true,nodeReducer:(node,data)=>{const hidden=!!analysis.nodes&&!analysis.nodes.has(node),match=query.trim()&&data.label.toLowerCase().includes(query.trim().toLowerCase()),community=communities[node];if(hidden)return{...data,hidden:true};if(selected&&node!==selected)return{...data,color:"#c6bdc1",zIndex:0,label:match?data.label:""};return{...data,color:community!==undefined?palette[community%palette.length]:match?"#d94e80":data.color,size:match?data.size*1.8:data.size,zIndex:match||node===selected?3:1}},edgeReducer:(edge,data)=>{const[s,t]=graph.extremities(edge),hidden=!!analysis.nodes&&(!analysis.nodes.has(s)||!analysis.nodes.has(t));if(hidden)return{...data,hidden:true};const onPath=pathEdges.has([s,t].sort().join("\u0000"));if(onPath)return{...data,color:"#d94e80",size:3,zIndex:4};if(selected)return s===selected||t===selected?{...data,color:"#6f183f",size:data.size*2,zIndex:2}:{...data,hidden:true};return data}});
  renderer.on("clickNode",({node})=>setSelected(node));renderer.on("clickStage",()=>setSelected(null));graphRef.current=graph;rendererRef.current=renderer;return()=>{renderer.kill();rendererRef.current=null;graphRef.current=null}
 },[visible,query,selected,analysis,communities,pathEdges]);

 function runLayout(){const graph=graphRef.current;if(!graph||graph.order<2)return;setLayoutRunning(true);const layout=new FA2Layout(graph,{settings:{gravity:1,scalingRatio:12,strongGravityMode:false,slowDown:8,barnesHutOptimize:true,barnesHutTheta:.5}});layout.start();window.setTimeout(()=>{layout.stop();setLayoutRunning(false);rendererRef.current?.getCamera().animatedReset({duration:600})},4000)}
 function focusSearch(value:string){setQuery(value);if(!value.trim())return;const found=visible.nodes.find(n=>n.label.toLowerCase().includes(value.trim().toLowerCase()));if(found){const pos=graphRef.current?.getNodeAttributes(found.id);if(pos)rendererRef.current?.getCamera().animate({x:pos.x,y:pos.y,ratio:.18},{duration:500})}}
 function createEgo(){const graph=graphRef.current;if(!graph||!selected)return;const nodes=new Set<string>([selected,...graph.neighbors(selected)]);setAnalysis({title:`Subgrafo de “${selected}”`,description:`Concepto central y ${nodes.size-1} conceptos relacionados directamente.`,nodes});setSelected(null)}
 function findPath(){const graph=graphRef.current;if(!graph)return;const path=shortestPath(graph,pathFrom,pathTo);if(!path){setAnalysis({title:"Sin camino",description:"No existe un camino entre los conceptos con los filtros actuales.",nodes:new Set()});return}setAnalysis({title:"Camino conceptual",description:`${path.length-1} pasos conectan “${pathFrom}” con “${pathTo}”.`,nodes:new Set(path),path});setSelected(null)}
 function detectCommunities(){const graph=graphRef.current;if(!graph)return;setBusy("Detectando comunidades…");setTimeout(()=>{const result=louvain(graph,{getEdgeWeight:"weight"});setCommunities(result);const counts=new Map<number,number>();Object.values(result).forEach(c=>counts.set(c,(counts.get(c)??0)+1));const largest=[...counts.entries()].sort((a,b)=>b[1]-a[1])[0];setAnalysis({title:`${counts.size} comunidades`,description:`La comunidad más grande reúne ${largest?.[1]??0} conceptos. Los colores muestran agrupaciones densamente conectadas.`,nodes:null});setBusy("")},30)}
 function showCommunity(id:number){const nodes=new Set(Object.entries(communities).filter(([,c])=>c===id).map(([n])=>n));setAnalysis({title:`Comunidad ${id+1}`,description:`Subgrafo temático de ${nodes.size} conceptos.`,nodes})}
 function calculateCentrality(metric:"degree"|"weighted"|"pagerank"|"betweenness"){const graph=graphRef.current;if(!graph)return;setBusy("Calculando centralidad…");setTimeout(()=>{let scores:Record<string,number>;if(metric==="degree")scores=Object.fromEntries(graph.nodes().map(n=>[n,graph.degree(n)]));else if(metric==="weighted")scores=Object.fromEntries(graph.nodes().map(n=>[n,weightedDegree(graph,n,"weight")]));else if(metric==="pagerank")scores=pagerank(graph,{getEdgeWeight:"weight"});else scores=betweennessCentrality(graph,{getEdgeWeight:null,normalized:true});const ranking=Object.entries(scores).map(([id,value])=>({id,value})).sort((a,b)=>b.value-a.value).slice(0,30),nodes=new Set(ranking.map(x=>x.id));setAnalysis({title:`Centralidad: ${metric}`,description:"Los 30 conceptos con mayor puntuación. Una puntuación alta indica una posición estructuralmente relevante, no necesariamente mayor importancia narrativa.",nodes,ranking});setBusy("")},30)}
 async function loadFiles(event:ChangeEvent<HTMLInputElement>){const files=[...(event.target.files??[])],nf=files.find(f=>/nodes/i.test(f.name)),ef=files.find(f=>/edges/i.test(f.name));if(!nf||!ef){setStatus("Selecciona property_graph_nodes.csv y property_graph_edges.csv");return}setStatus("Leyendo los archivos localmente…");try{const[nr,er]=await Promise.all([nf.text(),ef.text()]),n=parseCsv(nr),e=parseCsv(er);const nodes=n.map(r=>({id:r.concept,label:r.label||r.concept,frequency:Number(r.frequency)||0,sentenceFrequency:Number(r.sentence_frequency)||0,documentFrequency:Number(r.document_frequency)||0,pos:r.pos||""})),edges=e.map(r=>({source:r.source,target:r.target,weight:Number(r.weight)||1,sentenceIds:r.sentence_ids||"",documentIds:r.document_ids||""}));if(!nodes.length||!edges.length)throw new Error();setDataset({nodes,edges,name:"Grafo de propiedades cargado"});setMaxNodes(nodes.length);setMinWeight(1);setSelected(null);setQuery("");setCommunities({});setAnalysis({title:"Grafo completo",description:"Vista general del vocabulario.",nodes:null});setStatus(`${nodes.length.toLocaleString("es")} conceptos · ${edges.length.toLocaleString("es")} relaciones`)}catch{setStatus("No se pudieron leer los CSV. Comprueba sus columnas.")}event.target.value=""}
 function exportSubgraph(){const ids=analysis.nodes??new Set(visible.nodes.map(n=>n.id)),nodes=dataset.nodes.filter(n=>ids.has(n.id)),edges=dataset.edges.filter(e=>ids.has(e.source)&&ids.has(e.target));for(const[name,content]of[["subgrafo_nodes.csv",["concept,label,frequency,sentence_frequency,document_frequency,pos",...nodes.map(n=>[n.id,n.label,n.frequency,n.sentenceFrequency,n.documentFrequency,n.pos].map(v=>`"${String(v).replaceAll('"','""')}"`).join(","))].join("\n")],["subgrafo_edges.csv",["source,target,weight,sentence_ids,document_ids",...edges.map(e=>[e.source,e.target,e.weight,e.sentenceIds,e.documentIds].map(v=>`"${String(v).replaceAll('"','""')}"`).join(","))].join("\n")]]as const){const url=URL.createObjectURL(new Blob([content],{type:"text/csv"})),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}}

 const communityList=Object.entries(Object.values(communities).reduce((a,c)=>(a[c]=(a[c]??0)+1,a),{} as Record<number,number>)).sort((a,b)=>b[1]-a[1]);
 return <main className="app-shell">
  <header className="topbar"><div className="brand-mark">f<span>IA</span></div><div><p className="eyebrow">furIAtecnotravesti · Fundación Furia Trans</p><h1>Atlas de conceptos</h1></div><div className="privacy-pill"><i/> análisis local · datos privados</div></header>
  <section className="workspace"><aside className="sidebar analysis-sidebar">
   <label className="file-card compact"><span className="file-icon">↑</span><strong>Cargar grafo</strong><small>nodes.csv + edges.csv</small><input type="file" multiple accept=".csv,text/csv" onChange={loadFiles}/></label><p className="load-status"><span className="live-dot"/>{status}</p>
   <nav className="tabs">{(["explorar","caminos","comunidades","centralidad","comprender"]as Tab[]).map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</nav>
   {tab==="explorar"&&<div className="tool-section"><h2>Explorar</h2><label>Buscar concepto</label><div className="search-wrap"><span>⌕</span><input value={query} onChange={e=>focusSearch(e.target.value)} placeholder="Escribe un término…"/><button onClick={()=>setQuery("")}>×</button></div><div className="control"><div><span>Peso mínimo</span><b>{minWeight}</b></div><input type="range" min="1" max={Math.max(2,Math.min(50,Math.max(...dataset.edges.map(e=>e.weight))))} value={minWeight} onChange={e=>setMinWeight(Number(e.target.value))}/></div><div className="control"><div><span>Máximo de nodos</span><b>{maxNodes}</b></div><input type="range" min="50" max={Math.max(50,dataset.nodes.length)} step="50" value={Math.min(maxNodes,Math.max(50,dataset.nodes.length))} onChange={e=>setMaxNodes(Number(e.target.value))}/></div>{selected&&<button className="primary-button" onClick={createEgo}>Crear subgrafo de {selected}</button>}</div>}
   {tab==="caminos"&&<div className="tool-section"><h2>Caminos</h2><p>Identifica los conceptos intermedios que conectan dos términos.</p><label>Origen</label><input className="text-field" list="concepts" value={pathFrom} onChange={e=>setPathFrom(e.target.value)}/><label>Destino</label><input className="text-field" list="concepts" value={pathTo} onChange={e=>setPathTo(e.target.value)}/><datalist id="concepts">{visible.nodes.map(n=><option key={n.id} value={n.id}/>)}</datalist><button className="primary-button" onClick={findPath}>Buscar camino más corto</button>{analysis.path&&<ol className="path-list">{analysis.path.map(n=><li key={n}>{n}</li>)}</ol>}</div>}
   {tab==="comunidades"&&<div className="tool-section"><h2>Comunidades</h2><p>Agrupa conceptos que coaparecen más entre sí que con el resto del vocabulario.</p><button className="primary-button" onClick={detectCommunities}>Detectar con Louvain</button><div className="community-list">{communityList.slice(0,20).map(([id,count])=><button key={id} onClick={()=>showCommunity(Number(id))}><i style={{background:palette[Number(id)%palette.length]}}/><span>Comunidad {Number(id)+1}</span><b>{count}</b></button>)}</div></div>}
   {tab==="centralidad"&&<div className="tool-section"><h2>Centralidad</h2><p>Compara distintas formas de identificar conceptos estructuralmente relevantes.</p><button onClick={()=>calculateCentrality("degree")}>Grado · más conexiones</button><button onClick={()=>calculateCentrality("weighted")}>Grado ponderado · coaparición</button><button onClick={()=>calculateCentrality("pagerank")}>PageRank · influencia</button><button onClick={()=>calculateCentrality("betweenness")}>Intermediación · puentes</button>{analysis.ranking&&<ol className="ranking">{analysis.ranking.map(x=><li key={x.id}><span>{x.id}</span><b>{x.value.toFixed(4)}</b></li>)}</ol>}</div>}
   {tab==="comprender"&&<div className="tool-section"><h2>Comprender el vocabulario</h2><div className="insight-grid"><div><b>{visible.nodes.length}</b><span>conceptos</span></div><div><b>{visible.edges.length}</b><span>relaciones</span></div><div><b>{summary.averageDegree.toFixed(1)}</b><span>grado medio</span></div><div><b>{summary.averageWeight.toFixed(1)}</b><span>coaparición media</span></div></div><h3>Cómo leerlo</h3><p><strong>Frecuencia</strong> señala presencia textual. <strong>Centralidad</strong> señala posición en la red. <strong>Comunidades</strong> sugieren constelaciones temáticas. <strong>Caminos</strong> muestran mediaciones entre conceptos.</p><p className="method-note">Estas medidas ayudan a formular preguntas; no sustituyen la lectura situada de las narrativas ni convierten la proximidad textual en causalidad.</p></div>}
   <div className="analysis-summary"><strong>{analysis.title}</strong><span>{analysis.description}</span>{analysis.nodes&&<button onClick={()=>setAnalysis({title:"Grafo completo",description:"Vista general del vocabulario.",nodes:null})}>Volver al grafo completo</button>}<button onClick={exportSubgraph}>↓ Exportar vista/subgrafo</button></div><p className="ownership">Procesamiento local. Datos privados y propiedad de la <strong>Fundación Furia Trans</strong>.</p>
  </aside><section className="graph-panel"><div className="graph-toolbar"><div><span className="live-dot"/>{busy||dataset.name}</div><button onClick={runLayout} disabled={layoutRunning}>{layoutRunning?"Organizando…":"ForceAtlas2"}</button><button onClick={()=>rendererRef.current?.getCamera().animatedReset({duration:500})}>Centrar</button><button onClick={()=>rendererRef.current?.getCamera().animatedUnzoom({duration:250})}>−</button><button onClick={()=>rendererRef.current?.getCamera().animatedZoom({duration:250})}>+</button></div><div className="graph-stage"><div ref={containerRef} className="sigma-container"/><div className="legend"><span><i/> Concepto</span>{Object.keys(communities).length>0&&<span>Color = comunidad</span>}</div><p className="canvas-help">Arrastra · amplía · selecciona un concepto</p>{selectedNode&&<aside className="detail-card"><button onClick={()=>setSelected(null)}>×</button><p className="detail-kicker">Concepto seleccionado</p><h2>{selectedNode.label}</h2><div className="detail-metrics"><span><b>{selectedNode.frequency}</b>ocurrencias</span><span><b>{selectedNode.sentenceFrequency}</b>frases</span><span><b>{selectedNode.documentFrequency}</b>documentos</span></div><button className="primary-button" onClick={createEgo}>Crear subgrafo</button><h3>Relaciones más fuertes</h3><ul>{selectedEdges.map(e=><li key={`${e.source}-${e.target}`}><span>{e.source===selected?e.target:e.source}</span><b>{e.weight}</b></li>)}</ul></aside>}</div></section></section>
 </main>
}
